### ISSUE TITLE
ERROR: LoadError: UndefVarError: `run_code_blocks` not defined

### ISSUE THREAD

**Issue by ceferisbarov** [svilupp/Julia-LLM-Leaderboard#15]
Running `examples/create_definition.jl` script throws the following error:
```
ERROR: LoadError: UndefVarError: `run_code_blocks` not defined
```
`run_code_blocks_additive` is defined, but `run_code_blocks` is not.

**Comment by svilupp** [comment]
Thanks for spotting!
